### ISSUE TITLE
[Docs] 프로젝트 구조 논의

### ISSUE THREAD

**Issue by HoJongPARK** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#1]
## To-do
- [x] 프로젝트 폴더 구조 정의 [위키 - 링크](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/wiki/프로젝트-구조)
- [x] 브랜치 규칙 정의 [위키 - 링크](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/wiki/브랜치-작성-규칙)
- [x] 커밋 메시지 작성 규칙 정의 [위키 - 링크](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/wiki/커밋-메시지-작성-규칙)
