### ISSUE TITLE
[Feature] 온보딩 페이지

### ISSUE THREAD

**Issue by jsyworks** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#103]
## Description
온보딩 페이지 UI 구현

## Sketch Screenshot
<img width="250" src="https://user-images.githubusercontent.com/52963399/173815210-f356906a-e0fd-438c-bda9-ccd5c6022adf.png" /><img width="250" src="https://user-images.githubusercontent.com/52963399/173815221-e5d50665-a183-4b33-9343-f9849608fe4d.png" /><img width="250" src="https://user-images.githubusercontent.com/52963399/173815227-b89bfd44-2039-43b6-b66c-31381cf598c2.png" />

## To-do
- [x] Vstack을 이용해서 Text와 Image를 배치
- [x] 건너뛰기 기능 구현
- [x] 시작하기 버튼 기능 구현
- [x] .tabViewStyle(.page)로 온보딩 작동 구현
