### ISSUE TITLE
[Feature] 채팅방 UI 구현

### ISSUE THREAD

**Issue by HoJongPARK** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#107]
## Description
- 채팅방 UI 를 구현합니다

## Sketch Screenshot
<img width="300" alt="image" src="https://user-images.githubusercontent.com/57793298/173831270-ba14b0c5-9cdd-4c09-93b4-ad7693fd52a6.png">

## To-do
- [x] 내 메시지 View 구현하기
- [x] 상대방 메시지 View 구현하기
- [x] 입장 메시지 View 구현하기
- [x] 메시지 리스트 View 구현하기
