### ISSUE TITLE
[Feature] 마이팟 데이터 바인딩

### ISSUE THREAD

**Issue by YoonyoungL** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#109]
## Description
마이팟 데이터 바인딩을 진행합니다.

## To-do
- [x] 마이팟 뷰모델 작성
- [x] 마이팟 리스트 가져오기
- [x] 마이팟 택시팟 나가기
