### ISSUE TITLE
[Feature] User Data Layer 구현

### ISSUE THREAD

**Issue by HoJongPARK** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#12]
## Description
User Data Layer 를 구현합니다.

## To-do
- [x] User Repository Protocol 정의
- [x] User Repository Protocol 을 구현하는 Firebase DataSource 구현
- [x] User Repository Test 작성 & 통과 확인

## Etc
- [Project Architecture](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/wiki/데이터-모델링)
