### ISSUE TITLE
[Feature] 달력 모달 날짜 선택에 따른 

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#124]
## 선행 작업
- [x] #121
- [x] #111 

## Description
모달 확인 버튼 눌름에 따라 해당 날짜 위치로 scroll 이동

## To-do
- [x] party list view renderedDate state 변수 생성
- [x] scrollview reader 생성
- [x] scroll view proxy modal 인자로 넘겨주기
- [x] proxy의 scroll to 함수 구현

**Comment by SH0123** [comment]
https://www.hackingwithswift.com/quick-start/swiftui/how-to-make-a-scroll-view-move-to-a-location-using-scrollviewreader
