### ISSUE TITLE
[Feature] Chatting Data Layer 구현

### ISSUE THREAD

**Issue by HoJongPARK** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#13]
## Description
Chatting Data Layer 를 구현합니다.

## To-do
- [x] Chatting Repository Protocol 정의
- [x] Chatting Repository Protocol 을 구현하는 Firebase Data Source 구현
- [x] Chatting Repository 테스트 코드 작성 & 통과 확인
## Etc
- [Project Architecture](https://github.com/DeveloperAcademy-POSTECH/MC2-Team3-SSAK3/wiki/데이터-모델링)
