### ISSUE TITLE
[Feature] TODO 제거

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#138]
## Description
남은 TODO를 제거합니다.

## To-do
- [x] 프로필뷰 특수문자 제외
- [x] 정보 확인 뷰에 요일 추가
- [x] 정보 확인 뷰의 배경을 머터리얼로 구현
