### ISSUE TITLE
[Feature] 마이팟 셀뷰 추가 및 변경

### ISSUE THREAD

**Issue by YoonyoungL** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#142]
## Description
마이팟에 구현되어있는 셀뷰를 연결할예정이고
셀뷰에서 작은 디자인 수정이 있습니다.

## Sketch Screenshot
<img width="200" alt="image" src="https://user-images.githubusercontent.com/58019653/174090006-12e6b3bc-f59f-4e39-a58c-4a0f473afc42.png">

## To-do
- [x] 셀뷰 구조 변경
- [x] 셀뷰 디자인 수정
- [x] 마이팟에 셀뷰 연결
