### ISSUE TITLE
[Feature] UI 수정

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#146]
## Description
어색한 UI를 수정합니다.

## To-do
- [x] 프로필 관리 화면에서 '저장' 버튼 누르면 바로 닫히도록
- [x] 닉네임 autoCapitalization true로
- [x] jpeg 압축률 0.1로 낮추기
- [x] 프로필 사진 플레이스홀더 바꾸기
- [x] 머터리얼 모달 적용
- [x] Taxi, Train 이미지 에셋에 다시 넣기
- [x] 정보 확인 뷰 라운드 버튼에 ProgressView 적용
