### ISSUE TITLE
[Refactor] 뷰모델 코드 리팩토링

### ISSUE THREAD

**Issue by HoJongPARK** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#155]
## Description
- 현재 택시팟 리스트와 마이팟 리스트는 서로 다른 택시팟 리스트를 가지고 있다.
- 하지만 택시팟 리스트의 개수가 많지 않다는 점, 또한 택시팟 생성 시  어색한 data flow (서로 다른 ViewModel 이 데이터를 통신해야함) 를 해결하기 위해 리스트를 전체적으로 관리하는 viewModel 로 통합하려고 한다. 
- 해당 viewModel 은 user 정보를 같이 가지고 있고, 또한 environmentObject 변수로 언제 어디서든 접근 가능하게 구현할 생각이다.

## To-do
- [x] 택시팟 리스트, 유저 정보를 가지고 있는 Environment viewModel 생성
- [x] 택시팟 리스트 viewModel 갈아 끼우기
- [x] 마이 택시팟 리스트 viewModel 갈아 끼우기
