### ISSUE TITLE
[Feature] Delete TODOs and Fix ChatRoomView

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#159]
## Description
남은 TODO 제거 및 ChatRoomView에서 어색한 부분 수정

## To-do
- [x] 저번 PR때 적용 안 된 부분 다시 적용
- [x] 남아있는 TODO들 제거 (SwiftLint 경고, 구현 안된 TODO)
- [x] 채팅방에서 나가기 버튼 구현
- [x] 채팅방 타이틀 00분이 0분으로 표시되는 것 수정
- [x] 채팅방에 현재 인원수 표시
- [x] 키보드에 따라 채팅이 올라갔다가 내려가도록
