### ISSUE TITLE
[Feature] 회원가입

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#17]
## Description
약관 동의 페이지
회원가입 페이지

## Figma Screenshot
<img width="250" alt="스크린샷 2022-06-08 오전 10 04 49" src="https://user-images.githubusercontent.com/26588989/172509531-c5d704fd-b956-4e4f-ab67-355be0b436de.png"> <img width="250" alt="스크린샷 2022-06-08 오전 10 04 56" src="https://user-images.githubusercontent.com/26588989/172509539-e41a3d91-162b-477d-b6dd-1728958ddb1d.png"> <img width="250" alt="스크린샷 2022-06-08 오전 10 08 44" src="https://user-images.githubusercontent.com/26588989/172509724-504c1734-fb5e-4ef3-b45f-b1d4e53b50ed.png">

## To-do
- [ ] checkbox style 이용하여 약관 동의 페이지 구성
- [x] UserDefaults를 이용하여 회원가입 여부 체크
- [x] underline만 있는 스타일의 TextField 생성
- [x] 가입코드 프론트에서 체크하여 인증 완료 text display
- [x] 다음, 가입 완료 버튼 component 만들기 전까지는 임의로 만들어서 logic만 구현해둘 것
- [x] textfield 값 모두 채워지지 않았을 경우 button disabled
- [x] 닉네임은 중복 체크 X

## Etc
- [ ] 닉네임 오전, 오후 구분할 수 있도록 요구하는 워딩은 어떻게 하면 좋을까요?
