### ISSUE TITLE
[Feature] 마이페이지

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#18]
## Description
- 프로필 관리 - 닉네임, 프로필 사진 변경
- 알림 설정
- 로그아웃, 회원탈퇴

## Sketch Screenshot
<img width="200" alt="image" src="https://user-images.githubusercontent.com/75792767/172511120-950fd520-6271-4820-bfa7-ea9efab0d454.png">

## To-do
- [x] 요소 전부 추가해놓기
- [ ] 디자인 입히기
- [ ] UserDefaults에 알림 설정 저장
- [ ] 알림 설정 연결
- [ ] 사진 피커
- [ ] 닉네임, 프로필 사진 파이어베이스와 연결
- [ ] 로그아웃, 회원탈퇴 구현
