### ISSUE TITLE
[Feature] 정보 확인

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#20]
## Description
택시팟 참여하기 직전 택시팟에 대한 정보를 확인하고 참여를 결정 할 수 있는 페이지.

## Sketch Screenshot
<img width="200" alt="image" src="https://user-images.githubusercontent.com/75792767/172511878-de3e0768-58e3-4d10-bfb5-758d2b24bf3b.png">

## To-do
- [ ] 뷰 요소 전부 추가
- [ ] 디자인 입히기
- [ ] 날짜, 시간, 방향, 명단, 참여하기 버튼, 취소버튼 표시
- [ ] 이전 화면에서 택시팟 정보 불러오기
- [ ] 참여하기 버튼 클릭시 탭 이동 + 내비게이션링크
- [ ] 참여하기 버튼 클릭시 파이어베이스에 멤버 추가
- [ ] 참여하기 버튼 클릭시 참여 메시지 채팅방에 자동 전송

## Etc
