### ISSUE TITLE
[Feature] 택시팟 리스트

### ISSUE THREAD

**Issue by pis3120** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#21]
## Description
탭뷰의 첫번째 화면인 "택시팟" UI를 구현할 예정입니다.

## To-do
- [ ] LazyVStack로 현재 생성되어 있는 모든 택시팟 채팅방 CellView를 로딩하여 보여준다.
- [ ] ScrollView 밑에 LazyVStack를 구현하여 채팅방 CellView를 스크롤하여 볼 수 있도록 한다.
- [ ] CellView를 날짜별로 Daily 구별하여 보여주어야 한다.
- [ ] 택시팟 CellView를 선택하면 '아보'가 구현한 택시팟 정보 View와 연동 예정
- [ ] "+" 버튼을 UI 오른쪽 상단에 구현하여, '호종E'가 만든 택시팟 생성 View와 연동 예정
- [ ] "날짜 선택" 버튼을 UI에 구현하여, '레이몬드'가 만든 half-modal 달력과 연동 예정

## Etc
1. LazyVStack / VStack / List 생각해보기
Loading할 데이터가 많으면 LazyVStack이 필수겠지만, 이번 프로젝트에서는 VStack또는 List로 구현해도 될 것같은 생각이 든다.
확장성 및 사용량을 고려하여 LazyVStack로 미리 구현해보는 것도 좋을지도.
(이전 프로젝트때는 LazyVStack으로 Dumy데이터 셀을 불러와서 구현하였음.)

**Comment by SH0123** [comment]
LazyVStack을 깜빡하고 LazyVGrid로 쓰신 것 같아요 ~
@pis3120

**Comment by pis3120** [comment]
레이몬드 확인 땡큐~!

**Comment by pis3120** [comment]
> 참고로 밑으로 당겨서 새로고침을 구현하려는 경우 List 를 활용하면 쉽게 refreshable 이란 modifier 를 사용할 수 있습니다. List 로 구현하는 것도 괜찮을 것 같네요

오오 좋은정보 감사해요~!
