### ISSUE TITLE
[Refactor] 수식으로 변환하고 있는 날짜, 시간 처리 로직 formatter로 변환 

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#226]
## Description
```swift
self.meetingMonth = taxiParty.meetingDate / 100 % 100
self.meetingDay = taxiParty.meetingDate % 100
self.meetingHour = String(format: "%02d", taxiParty.meetingTime / 100 % 100)
self.meetingMinute = String(format: "%02d", taxiParty.meetingTime % 100)
```
이러한 처리 로직을 dateFormatter를 이용하는 것으로 방법을 바꿔 처리 로직을 캡슐화함

## To-do
- [ ] HH:mm 형식으로 전환하는 foramtter는 cell과 chat room 모두에서 사용되므로 global 요소로 작성
- [ ] 위의 meetingMonth와 meetingDay는 사용되지 않으므로 제고
- [ ] TaxiPartyInfoView에서 사용되는 formatter는 해당 파일에 private 하게 작성
