### ISSUE TITLE
[Feature] 택시팟 CellView

### ISSUE THREAD

**Issue by pis3120** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#23]
## Description
첫번째 탭뷰인 "택시팟" / 두번째 탭뷰인 "마이팟" 에서 사용할 CellView

## Sketch Screenshot
<img width="399" alt="image" src="https://user-images.githubusercontent.com/40324511/172515275-6c5ef8be-2b56-4f27-99e2-e03d6f16e991.png">

## To-do
- [ ] "출발지->목적지" 정보 명시
- [ ] 택시 "탑승시간" 명시
- [ ] 택시팟 참여자 "프로필 이미지" 보이게 구현
- [ ] 택시팟 현재 "참여자 및 최대숫자" 명시

## etc
1. HStack 및 VStack을 적절히 사용 예정
2. RoundedRectangle를 활용하여 Hi-Fi 디자인 요건에 맞추기
3. Text 필드 및 Image에 변수를 활용하여 필요한 데이터를 적절히 불러오기

**Comment by HoJongPARK** [comment]
기정의된 **TaxiParty** 데이터 모델을 받아서 해당 정보를 Text 나 이미지에 사용하는 것으로 방향을 잡으면 될 것 같습니다.
