### ISSUE TITLE
[Feature] 채팅방 View 구현

### ISSUE THREAD

**Issue by YoonyoungL** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#25]
## Description
참여하면 연결될 채팅방 구현

## Screenshot
추후 추가 예정

## To-do
- [ ] 내가 보낸 메시지
- [ ] 채팅방 입장 메시지
- [ ] 상대방이 보낸 메시지
- [ ] 채팅 리스트
