### ISSUE TITLE
[Feature] 파티 리스트 셀 참여중 표시 추가

### ISSUE THREAD

**Issue by YoonyoungL** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#261]
## Description
참여중일 때 참여중이라고 표시되도록 UI 변경

## Sketch Screenshot
<img width="383" alt="스크린샷 2022-09-28 오전 12 13 11" src="https://user-images.githubusercontent.com/58019653/192565549-6d8ec0a2-a784-4ce5-a310-09e54a783be2.png">

## To-do
- [x] 셀에 참여중 표시 추가
- [x] 현재 파티에 참여 중인지 확인하는 코드 작성
- [x] 모든 파티를 불러오도록 변경
