### ISSUE TITLE
[Feature] 계좌번호 간편 전송 매크로

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#266]
## Description
계좌번호 간편 송금 매크로 구현
채팅 입력창에서 송금 버튼을 누르면 은행과 계좌번호를 포함한 메세지가 전송됩니다
은행과 계좌번호가 등록되어있지 않은 경우 등록할 수 있는 하프모달이 나타납니다
하프모달에서 등록한 은행과 계좌번호는 설정창의 은행, 계좌번호 입력 칸에서 확인할 수 있습니다

## Sketch Screenshot
<img width="300" alt="스크린샷 2022-10-10 오후 2 10 03" src="https://user-images.githubusercontent.com/26588989/194802533-dbe2c311-644c-4623-8219-191be71b0551.png">

## To-do
- [ ] 채팅 입력창 송금 버튼 구현
- [ ] 송금 버튼 선택시 메세지 전송
- [ ] keyChain에 계좌번호 및 은행 CRUD 구현
- [ ] 하프모달 및 해당 UI 구현
