### ISSUE TITLE
[Bug] 택시팟 참가 로직 수정

### ISSUE THREAD

**Issue by HoJongE** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#274]
## Description
Server side에서 최신 택시팟 정보를 조회하고, 참가 처리하는 것은 동시에 여러 요청이 왔을 때 정원을 초과해서 참가할 수 있는 오류를 낳을 수 있습니다.
이를 해결하기 위해서 firestore에서 지원하는 트랜잭션을 통해 여러 택시팟 참가 요청이 올 때 정원을 초과해서 참가하는 현상이 없도록 수정해야 합니다.

## To-do
- [x] 현재 로직에서 Unit test 작성을 통해 비정상적으로 택시팟에 참가할 수 있는지를 확인한다.
- [x] 택시팟 참가 로직을 트랜잭션을 사용하도록 변경한다. 
- [x] Unit test 작성을 통해 동시에 많은 요청이 있더라도 비정상적인 참가가 없는지를 확인한다.

## Etc
- Firestore는 noSql 으로, 모든 트랜잭션의 격리 수준은 Serializable 수준임
- 트랜잭션은 항상 실패하거나 모두 성공한다. 또한 트랜잭션 도중 다른 operation이 트랜잭션에서 추적하는 document를 수정하면, 트랜잭션은 실패하고 유한한 횟수만큼 다시 시도한다.
- 트랜잭션을 사용하도록 변경하더라도, 모든 유저가 새로운 버전으로 업데이트 하기 전까지 function 을 삭제하면 안된다.

## References
- https://firebase.google.com/docs/firestore/transaction-data-contention?authuser=0
