### ISSUE TITLE
[Feature] Taxi Party List Use case 추가

### ISSUE THREAD

**Issue by HoJongPARK** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#36]
## Description
- 택시팟 추가 유즈케이스를 추가합니다.

## To-do
- [x] 택시팟 조회 유즈케이스
- [x] 택시팟 생성 유즈케이스
- [x] 택시팟 참가 유즈케이스
