### ISSUE TITLE
[Feature] ProfileView 유저 프로필 변경 기능 구현(더미데이터 이용)

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#40]
## 선행 작업
- [x] #33 

## Description
유저 더미데이터를 이용하여, 닉네임 변경과 프로필 사진 변경 기능을 구현

## Sketch Screenshot
<img width="250" alt="image" src="https://user-images.githubusercontent.com/75792767/173023734-6297eaf6-91f6-4b9a-b1a5-fd77c924ac0b.png">

## To-do
- [x] User 더미데이터 생성
- [x] 사진 피커 구현
- [x] SDWebImageSwiftUI 적용
- [x] 사진 변경 구현
