### ISSUE TITLE
[Feature] 출발, 도착 장소를 나타내는 Place enumeration case 추가

### ISSUE THREAD

**Issue by HoJongPARK** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#42]
## Description
아래 스크린샷과 같이, 출발 장소를 정하는 부분이 추가되었음. 이에 따라 TaxiParty 모델이 변경되고, Place 에 장소를 추가해야함
## Sketch Screenshot
<img width="162" alt="image" src="https://user-images.githubusercontent.com/57793298/173057696-ab23f6a9-bb95-42f5-b274-7cf239dbd00a.png">

## To-do
- [x] Place enum 에 장소 추가
- [x] 도착지 별 출발 장소를 반환하는 프로퍼티 추가
- [x] TaxiParty 모델 변경
