### ISSUE TITLE
[Feature] TaxiPartyInfoView mockData 적용

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#52]
## 선행 작업
- [x] #49 
- [x] #42 

## Description
TaxiParty 더미데이터를 이용하여 택시팟 정보 표시

## Sketch Screenshot
<img width="250" alt="image" src="https://user-images.githubusercontent.com/75792767/173180617-d42e5183-85ac-48c2-982a-cbaedbcacea7.png">

## To-do
- [x] TaxiParty 더미데이터 추가
- [ ] 더미데이터로 택시팟 정보 표시(날씨, 방향, ...)
- [x] 택시팟에 현재 참가해있는 멤버 정보 표시
- [x] 택시팟 최대인원과 현 참가인원에 따라 달라지는 UI 고려
