### ISSUE TITLE
[Feature] 달력 컴포넌트 hifi에 맞춰 수정

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#59]
## 선행 작업
- [x] #22 

## Description
최종적으로 나온 hifi 디자인에 맞춰 달력을 최종 수정
다른 view의 컴포넌트로 사용될 때 action을 파라미터로 넣어 작동할 수 있도록 코드 구성

## Sketch Screenshot
<img width="300" alt="스크린샷 2022-06-13 오전 9 33 47" src="https://user-images.githubusercontent.com/26588989/173260296-ece16d3d-3282-40a3-b930-211d7e34b69a.png">

## To-do
- [x] 한 달 범위에서 벗어나는 달로는 이동 불가능하도록 mute 처리 및 버튼 비활성화
- [x] capsule 모양으로 선택된 날짜 표시
- [x] 선택에 상관없이 날짜 색과 dot 색 black
- [x] 달 이동 화살표 layout 조절
- [x] action 파라미터가 사용될 장소 적절히 조절 -> 달력이 사용되는 곳에 따라 switch 구문으로 표시하여 함수를 다르게 작성할 것인지 고민
