### ISSUE TITLE
[Feature] 달력 component 색상 최종

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#61]
## 선행 작업
- [x] #59 
## Description
hifi 디자인에 맞춰 색상과 글자 크기 변경

## Sketch Screenshot
<img width="300" alt="스크린샷 2022-06-13 오전 11 25 40" src="https://user-images.githubusercontent.com/26588989/173268576-7ae46829-797b-4ba4-92f6-6035dee49f37.png">

## To-do
- [x] 날짜 글자 크기
- [x] arrow 글자 크기 및 색상
- [x] muted day 색상
- [x] day 글자 크기 및 색상
- [x] selected capsule color, border
- [x] today capsule border
- [x] dot color
