### ISSUE TITLE
[Feature] TaxiPartyInfoView에 유즈케이스 적용

### ISSUE THREAD

**Issue by Chaeho-Min** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#67]
## 선행 작업
- [x] #49 
- [x] #52 

## Description
- 유즈케이스를 활용하여 실제 데이터와 연결

## To-do
- [x] User가 불러와지면 프로필 사진과 닉네임 화면에 뜨게 만들기
- [x] User가 불러와지지 않았을 때의 화면 만들기
- [x] 시작하기 버튼 눌렀을 때 택시팟에 참여하도록
