### ISSUE TITLE
[Feature] Use case Callback API 추가

### ISSUE THREAD

**Issue by HoJongPARK** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#69]
## Description
- 각 유즈 케이스 콜백 API 추가

## To-do
- [x] 택시팟 추가 API 추가
- [x] 택시팟 참가 API 추가
- [x] 택시팟 조회 API 추가
- [x] 인증 API 추가
- [x] 내 택시팟 API 추가

## Etc

@YoonyoungL @SH0123 @pis3120 @Chaeho-Min 
Combine 과 completion closure 중 원하는 걸 사용하시면 됩니다.
