### ISSUE TITLE
[Test] Usecase Test 추가

### ISSUE THREAD

**Issue by HoJongPARK** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#71]
## Description
Use case 가 잘 동작하는지 테스트를 추가해서 테스트해봅니다.

## To-do
- [x] 택시팟 참가 테스트
- [x] 택시팟 조회 테스트
- [x] 인증 유즈케이스 테스트
- [x] 내 택시팟 유즈케이스 테스트
