### ISSUE TITLE
[Feature] 회원가입 화면 hifi

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#73]
## Description
lofi 기준으로 하나의 화면에 나타내었던 가입 코드, 닉네임 화면 분할

## Sketch Screenshot
<img width="200" alt="스크린샷 2022-06-13 오후 8 56 58" src="https://user-images.githubusercontent.com/26588989/173348794-6d3e8407-5c15-4f40-a554-169ceff03f42.png"><img width="200" alt="스크린샷 2022-06-13 오후 8 57 06" src="https://user-images.githubusercontent.com/26588989/173348806-f074db32-178c-4102-b529-593262ec1119.png"><img width="200" alt="스크린샷 2022-06-13 오후 8 57 12" src="https://user-images.githubusercontent.com/26588989/173348811-2e4bfe22-d6ad-401f-8e31-2e08a1993e18.png"><img width="200" alt="스크린샷 2022-06-13 오후 8 57 24" src="https://user-images.githubusercontent.com/26588989/173348823-3eab3ee4-9f56-4747-a166-3e79e02aff07.png">

## To-do
- [x] 가입코드 화면과 닉네임 화면 분할
- [x] navigation 연결
- [x] textfield가 focused 됨에 따라 키보드 스타일 변경
- [x] 가입 코드 textfield underbar 색깔 변화 및 포커싱
- [x] 닉네임 textfield underbar 포커싱

**Comment by Chaeho-Min** [comment]
키보드가 올라올 때 버튼 스타일이 변경되게 한다면 지금 공통 컴포넌트로 있는 RoundedButton은 사용하지 않을 생각이신가요?

**Comment by SH0123** [comment]
@Chaeho-Min 일단은 찾아보지 않아서 모르겠지만 키보드 올라올 때 버튼을 따로 만들어서 조건에 따라 갈아끼우는 방식을 사용해보려 합니다.
좀 더 찾아봐야겠어요

**Comment by Chaeho-Min** [comment]
근데 제가 디자인 보면서 생각해본건데 저 화면들에서 키보드가 내려갈 일이 있나요?
키보드 계속 띄워놓고 진행하면 될 것 같은데요?

**Comment by SH0123** [comment]
focus를 처음부터 줘서 키보드를 뛰워놓고 하면 되겠다는거죠?
처음부터 focus를 줘도 화면 전환 될 때 찰나의 순간에 키보드가 내려가있는 순간이 있을수도 있을 것 같은데
일단 구현을 해봐야겠군요

**Comment by SH0123** [comment]
focus를 처음부터 줘서 키보드를 뛰워놓고 하면 되겠다는거죠?
처음부터 focus를 줘도 화면 전환 될 때 찰나의 순간에 키보드가 내려가있는 순간이 있을수도 있을 것 같은데
일단 구현을 해봐야겠군요

**Comment by HoJongPARK** [comment]
> focus를 처음부터 줘서 키보드를 뛰워놓고 하면 되겠다는거죠?
> 처음부터 focus를 줘도 화면 전환 될 때 찰나의 순간에 키보드가 내려가있는 순간이 있을수도 있을 것 같은데
> 일단 구현을 해봐야겠군요

찰나의 순간에 키보드가 내려가더라도 버튼이 있으니까 부자연스럽진 않을 것 같아요
