### ISSUE TITLE
[Feature] Color extension에 색상 추가, text style 추가

### ISSUE THREAD

**Issue by SH0123** [DeveloperAcademy-POSTECH/MC2-Team3-SSAK3#75]
## Description
text style, color 빠진 부분 추가

## Sketch Screenshot
UI 구현의 경우 Sketch 나 기타 디자인 툴의 스크린샷을 첨부합니다.

## To-do
- [x] signUpPlaceholder text style
- [x] signUpTitle text style
- [x] signUpExplain text style
- [x] signUpAgreement
- [x] custom green, signUpYellowGray
